#############
## this will update the vars.yml

---
- hosts: localhost
  
  vars:

    
  tasks:

  - name: change cas cache location
    lineinfile: 
      dest: vars.yml
      regexp: "CAS_DISK_CACHE:" 
      line: "     CAS_DISK_CACHE: /sastmp/cascache"

#  - name: add CAS UI path
#    lineinfile:
#      dest: vars.yml
#      insertafter: "CAS_DISK_CACHE:.*"
#      line: "     CAS_VIRTUAL_HOST: {{cas_virtual_host}}"


  - name: change saswork location
    blockinfile:
      dest: vars.yml
      insertafter: EOF
      marker: "# {mark} add saswork location"
      block: |
        SASV9_CONFIGURATION:
          1: '/* this will send the SASWORK to the /sastmp location */'
          2: 'WORK /sastmp/saswork'

  - name: set SASStudio folder root (remove if it exists)
    lineinfile:
      dest: vars.yml
      regexp: "webdms.showSystemRoot:"
      state: absent

  - name: set SASStudio folder root
    replace:
      dest: vars.yml
      regexp:  'STUDIO_CONFIGURATION:\n  init:'
      replace: 'STUDIO_CONFIGURATION:\n  init:\n    webdms.showSystemRoot: false'

  - name: set workspaceserver settings
    replace:
      dest: vars.yml
      regexp: '#FOUNDATION_CONFIGURATION:'
      replace: 'FOUNDATION_CONFIGURATION:'

  - name: set redshift access forwork spaceserver
    blockinfile:
      dest: vars.yml
      marker: '#{mark} add ws access to redshift'
      insertafter: '^FOUNDATION_CONFIGURATION:'
      block: |2
          1: ODBCINI=/opt/sas/spre/home/lib64/accessclients/odbc.ini
          2: ODBCINST=/opt/sas/spre/home/lib64/accessclients/odbcinst.ini
          3: ODBCHOME=/opt/sas/spre/home/lib64/accessclients
          4: LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$ODBCHOME/lib

  - name: set CAS Settings
    replace:
      dest: vars.yml
      regexp:  '#CAS_SETTINGS:'
      replace: 'CAS_SETTINGS:'

  - name: set ODBC home directory
    replace:
      dest: vars.yml
      regexp:  '#1: ODBCHOME=.*'
      replace: '1: ODBCHOME=/opt/sas/viya/home/lib64/accessclients'

  - name: set ODBCINI
    replace:
      dest: vars.yml
      regexp:  '#2: ODBCINI=.*'
      replace: '2: ODBCINI=$ODBCHOME/odbc.ini'

  - name: set LD_LIBRARY_PATH
    replace:
      dest: vars.yml
      regexp:  '#5: LD_LIBRARY_PATH=.*'
      replace: '5: LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$ODBCHOME/lib'

  - name: set pg host
    replace:
      dest: vars.yml
      regexp:  '\ \ deployTarget'
      replace: '  stateful'
      backup: yes

  - name: add additional pg hosts
    blockinfile:
      dest: vars.yml
      marker: '# {mark} add additional pg hosts'
      insertafter: '^INVOCATION_VARIABLES:'
      block: |2
          prog:
            sasdatasvrc:
            - NODE_NUMBER: '1'
              NODE_TYPE: S
              PG_PORT: '5432'
              SANMOUNT: '{{ SAS_CONFIG_ROOT }}/data/sasdatasvrc'
              SERVICE_NAME: postgres
          visual:
            sasdatasvrc:
            - NODE_NUMBER: '2'
              NODE_TYPE: S
              PG_PORT: '5432'
              SANMOUNT: '{{ SAS_CONFIG_ROOT }}/data/sasdatasvrc'
              SERVICE_NAME: postgres


  - name: Create sitedefault file, if it doesnt exist already
    file:
      path: roles/consul/files/sitedefault.yml
      state: touch


  - name: add config header line to sitedefault.yml if needed
    lineinfile:
      dest: roles/consul/files/sitedefault.yml
      state: present
      insertbefore: BOF
      line: "config:"

  - name: add applicaton header line to sitedefault.yml if needed
    lineinfile:
      dest: roles/consul/files/sitedefault.yml
      state: present
      insertafter: '^config:'
      line: '     application:'

  - name: set sharedVault backup location in sitedefault.yml
    blockinfile:
      dest: roles/consul/files/sitedefault.yml
      marker: '# {mark} set sharedVault'
      insertafter: 'application:'
      block: |2
                 sas.deploymentbackup:
                     sharedVault: /backups

  - name: set mail host and enable mail health check in sitedefault.yml
    blockinfile:
      dest: roles/consul/files/sitedefault.yml
      marker: '# {mark} set mail'
      insertafter: 'application:'
      block: |2
                 management.health.mail:
                     enabled: true
                 sas.mail:
                     host: localhost

  - name: set renderer baseUrl in sitedefault.yml
    blockinfile:
      dest: roles/consul/files/sitedefault.yml
      marker: '# {mark} set renderer baseUrl'
      insertafter: 'application:'
      block: |2
                 sas.reportrenderer.properties:
                     custom:
                         baseUrl: http://visual.viya.sas

  - name: set sasboot password in sitedefault.yml
    blockinfile:
      dest: roles/consul/files/sitedefault.yml
      marker: '# {mark} set sasboot pw'
      insertafter: 'application:'
      block: |2
                 sas.logon.initial.password: '{{sasboot_pw | b64decode }}'

  - name: set sitedefault permissions
    file:
      path: roles/consul/files/sitedefault.yml
      mode: 0600
